#!/bin/bash

PYTHON=$(python --version)

if ! [[ "$PYTHON" == Python* ]]; then
  echo "Make sure python is installed"
fi

if ! [[ $(where pylint) == *\pylint* ]]; then
  pip install pylint --upgrade
  pylint --version
fi

if ! [[ $(where pylint) == *\pylint* ]]; then
  echo "Something went wrong"
  exit 1
fi

STAGED_FILES=$(git diff --cached --name-only)
if [ "$STAGED_FILES" == "" ]; then
  echo "No files where staged"
  exit 1
fi

STAGED_FILES_ARRAY[0]=null

i=0
for FILE in $STAGED_FILES; do
  STAGED_FILES_ARRAY[i]=$FILE
  i=$((i+1))
done
echo "Validation python files now"

python .git/hooks/lint.py "${STAGED_FILES_ARRAY[*]}"
