#!/bin/bash

PYTHONVERSION=$(python -V)

case $PYTHONVERSION in
  Python*3.*)
  echo "$(python -V) is installed"
  commit_msg_path="$(readlink -f "./.git/COMMIT_EDITMSG")"
  chmod +x .git/hooks/prepare-commit-msg.py
  python .git/hooks/prepare-commit-msg.py "$1" "$2" "$3" "$commit_msg_path"
  result=$?
  ;;
  *)
  echo "NO PYTHON DETECTED"
  ;;
esac

echo ""
echo "$result"
#echo "Press something to exit"
#read -r junk

case $result in
  0)
    exit 0
    ;;
  1)
    exit 1
    ;;
  *)
    exit 2
    ;;
esac
