#!/bin/bash

SCRIPT_PATH=".git/hooks/python_scripts/"

PYTHON=$(python --version)

if ! [[ $(coverage --version) == *Coverage.py* ]]; then
  pip install coverage
  coverage --version
fi

if ! [[ $(coverage --version) == *Coverage.py* ]]; then
  echo "Something went wrong"
  exit 1
fi

if ! [[ "$PYTHON" == Python* ]]; then
  echo "Make sure python is installed"
  exit 1
fi

HEAD=".git/HEAD"

python "$SCRIPT_PATH"check_branch.py $HEAD
RESULT=$?
printf "\n"

if ! [ "$RESULT" == 0 ]; then
  echo "Exiting Hook"
  printf "\n"
  exit 1
fi

coverage run -m unittest discover
REPORT=$(coverage report)

python "$SCRIPT_PATH"coverage.py "$REPORT"
RESULT=$?

if ! [ "$RESULT" == 0 ]; then
  echo "Exiting Hook"
  printf "\n"
  exit 1
fi

exit 0
